<a href="https://colab.research.google.com/github/samuelkb/gColab/blob/main/notebooks/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducing NumPy

Python by itself is a good language but sometimes can be slow, specially when you work with ML / AI / DL. But fortunatelly, it does allow you to access to libraries that execute faster code written in languges like C.
NumPy is one such library, it provides fast alternatives to math operations in Python and is designed to work efficiently with groups of numbers - like matrices.

NumPy is a large library. In this notebook I will be updating some common uses, before to that, it could be interesting if you go and spend some time exploring its [documentation](https://docs.scipy.org/doc/numpy/reference/).

### Importing NumPy

The most used conventions you'll see is to name it "np" like so:

In [1]:
import numpy as np

Now you can use the library by prefixing the names of functions and types with np.

### Data types and shapes

The most common way to work with numbers in NumPy is through ndarray objects. They are similar to Python lists, but can have any number of dimensions. Also, ndarray supports fast math operations, which is just what we want.

Since it can store any number of dimensions, you can use ndarrays to represent any of the data types we covered before: scalars, vectors, matrices, or tensors.

### Scalars

[Scalars in NumPy](https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html) are a bit more involved than in Python. Instead of Python’s basic types like int, float, etc., NumPy lets you specify signed and unsigned types, as well as different sizes. So instead of Python’s int, you have access to types like uint8, int8, uint16, int16, and so on.

These types are important because every object you make (vectors, matrices, tensors) eventually stores scalars. And when you create a NumPy array, you can specify the type - **but every item in the array must have the same type.** In this regard, NumPy arrays are more like C arrays than Python lists.

If you want to create a NumPy array that holds a scalar, you do so by passing the value to NumPy's array function, like so:

In [2]:
s = np.array(5)

You can see the shape of your arrays by checking their `shape` attribute executing this code:

In [3]:
s.shape

()

For now, it is indicating us that it has zero dimensions.

Even though scalars are inside arrays, you still use them like a normal scalar. So we could type:

In [4]:
x = s + 3

And `X` would now equal to 8, and we can check the type of `X`, finding it is `numpy.int64`

In [5]:
print(x)

print(type(x))

8
<class 'numpy.int64'>


By the way, even scalar types support most of the array functions, so you can call ```x.shape```, and again it returns `()` because it has zero dimensions, even though it is not an array.

In [6]:
x.shape

()

If we try that with a normal Python scalar, we will get an error:

In [7]:
a = 10

print (a)

print(type(a))

a.shape

10
<class 'int'>


AttributeError: 'int' object has no attribute 'shape'

### Vectors

To create a vector, you'd pass a Python list to the `array` function, like this:

In [8]:
v = np.array([1,2,3])

Let's check its shape, we expect a single number representating the vector's one-dimensional length.

In [9]:
v.shape

(3,)

We can see that the shape is a tuple with the sizes of each of the `ndarray`'s dimensions. For scalars it was just an empty tuple, but vectors have one dimension, so the tuple includes a number and a comma.

You can access an element within the vector using indices, like this:

In [10]:
y = v[1]
print(y)

2


NumPy also supports advanced indexing techniques. For example, to access the items from the second element onward, you would say:

In [11]:
v[1:]

array([2, 3])

You can do a lot with NumPy indexing, I recommend you to read up on it [in the docs](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

According to docs, the basic slice syntax is ``i:j:k`` where ``i`` is the starting index, ``j`` is the stopping index, and ``k`` is the step (k $\neq$ 0). So we have the following:

In [12]:
x = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
print(x[1:7:2])

[10 30 50]


In [13]:
x = np.array([0, 11, 22, 33, 44, 55, 66, 77, 88, 99, 10, 20, 30, 40, 50])
x[1:10:4]

array([11, 55, 99])

### Matrices

To create matrices using NumPy you should use ```array``` function, as you did with vectors. However, instead of just passing in a list, you need to supply a list of lists, where each list represents a row.

To create a 3x3 matrix containing the numbers one through nine, you could do this:

In [14]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


If we check its ```shape``` attribute, we will recieve:

In [15]:
m.shape

(3, 3)

To access elements of matrices you will use indexes ```Row x Column```, for example, to access to number 6 of the above matrix, you can use:

In [16]:
print(m[1][2])

6


Here a little matrix shows how it indexes works in matrices:

In [17]:
matrix_order = np.array([['R0/C0','Col1','Col2','Col3'],['Row1',1,2,3],['Row2',4,5,6],['Row3',7,8,9]])
print(matrix_order)

[['R0/C0' 'Col1' 'Col2' 'Col3']
 ['Row1' '1' '2' '3']
 ['Row2' '4' '5' '6']
 ['Row3' '7' '8' '9']]


### Tensors

Tensors are just like vectors and matrices, but they can have more dimensions. To understand it, here an example of vector:

In [18]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

If you check its shape, you will find the following, also notice how it looks when we print the tensor:

In [19]:
t.shape

(3, 3, 2, 1)

In [20]:
print(t)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]


### Changing Shapes

Well, now you are familiar with how NumPy works with escalar, vectors, matrices and tensors. But you will discover that sometimes you would need to chang the shape of your data without actually changing its contents.
Let's say that we have a vector, witch is one-dimensional, but we need a matrix, wich is two-dimensional. To achieve that operation, we use ```reshape```function.
An example for better understanding:

In [21]:
v_to_reshape = np.array([10,20,30,40])
v_to_reshape.shape

(4,)

If we want a matrix 4x1, we can do this:

In [22]:
v_reshaped = v_to_reshape.reshape(4, 1)
v_reshaped.shape

(4, 1)

In [23]:
print(v_to_reshape)
print(v_reshaped)

[10 20 30 40]
[[10]
 [20]
 [30]
 [40]]


# Matrix operations with NumPy

We are familiar with scalar math, the normal addition, multiplication, and so on. When you work with neural networks, you might need to perform those sorts of operations with a lot of numbers (thousands and so on). As a programer, the first idea could be to iterate all values of a matrix with a for / while loop, but matrices affer a better alternative.

You can perform **Element-wise operations** what is treat items in the matrix individually and perform the same operation on each one. This notion also applies to data with any number of dimensions (yes, tensors as well). 

Adding two scalars is simple:
$$
2 + 5 = 7
$$

Adding a scalar and a matrics is practically the same thing:
$$
2 + \begin{bmatrix}1 & 2 \\3 & 4 \\\end{bmatrix} = \begin{bmatrix}2+1 & 2+2 \\2+3 & 2+4 \\\end{bmatrix} = \begin{bmatrix}3 & 4 \\5 & 6\\\end{bmatrix}
$$

For this to work, the matrices have to be the same shape. 

Adding a matrix to a second matrix is:
$$
\begin{bmatrix}1 & 3 \\5 & 7 \\\end{bmatrix} + \begin{bmatrix}2 & 4 \\6 & 8 \\\end{bmatrix} = \begin{bmatrix}1+2 & 3+4 \\5+6 & 7+8 \\\end{bmatrix} = \begin{bmatrix}3 & 7 \\11 & 15 \\\end{bmatrix}
$$

### The python way

Suppose you had a list of numbers, and you wanted to add `5` to every item in the list. Without NumPy, you might do something like this:

In [24]:
values = [1,2,3,4,5,6,7,8,9,10]
print(values)
for i in range(len(values)):
    values[i] += 5
print(values)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


That make sense and works with small data values, but it's a lot of code and it runs slowly because it's pure Python.

### The NumPy way

In NumPy, that operation can be complished doing the following:

In [25]:
values = [1,2,3,4,5,6,7,8,9,10]
print(values)
values = np.array(values) + 5
print(values)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 6  7  8  9 10 11 12 13 14 15]


Ok, maybe we cannot see with that example the benefits of NumPy, let's try a more complex example, we will create a big random list and then we will sum it an scalar:

In [34]:
import random
#Generate 5 random numbers between 0 and 5000
randomlist = []
randomlist = random.sample(range(0, 5000), 4900)
print("Creating a list with {} elements".format(len(randomlist)))

Creating a list with 4900 elements


In [36]:
%%timeit
for i in randomlist:
    values[i] += 5
print("values successfully increased")

IndexError: index 4137 is out of bounds for axis 0 with size 10

### Form a matrix with ranges

We can matrices with ranges using NumPy, as I show you in the next example:

In [38]:
print("1-Dimension array ")
print(np.arange(0,4))
print("2-Dimension array ")
print(np.array([np.arange(0,4), np.arange(5,9)]))

1-Dimension array 
[0 1 2 3]
2-Dimension array 
[[0 1 2 3]
 [5 6 7 8]]


We can also build matrices initializing with zeros or ones, by default float64 type of numbers are generated if not specified:

In [40]:
print("With zeros:")
print(np.zeros((5, 5)))
print("With ones:")
print(np.ones((3, 3), dtype=np.int16))

With zeros:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
With ones:
[[1 1 1]
 [1 1 1]
 [1 1 1]]


NumPy actually has functions for things like adding, multiplying, etc. But also supports using the standard math operators. So the following lines are equivalent:

In [44]:
some_array = np.arange(0,4)
print(some_array)
by_method = np.multiply(some_array, 5)
print(by_method)
by_scalar_op = some_array * 5
print(by_scalar_op)

[0 1 2 3]
[ 0  5 10 15]
[ 0  5 10 15]


### Adition

We can make two kinds of aditions over matrices:
- Adition of scalar
- Adition of matrix

In [52]:
m_1 = np.array([np.arange(1,4), np.arange(4,7)])
m_2 = np.array([np.arange(7,10), np.arange(10,13)])
print("Matrix_1: ")
print(m_1)
print("Matrix_2: ")
print(m_2)


# Scalar adition of 3 to each element in m_1
print("Scalar addition: ")
print(m_1 + 3)


# Matrix addition of m_1 and m_2
print("addition of two matrices of equal order: ")
print(m_1 + m_2)

Matrix_1: 
[[1 2 3]
 [4 5 6]]
Matrix_2: 
[[ 7  8  9]
 [10 11 12]]
Scalar addition: 
[[4 5 6]
 [7 8 9]]
addition of two matrices of equal order: 
[[ 8 10 12]
 [14 16 18]]


### Substraction

We can also do two kinds of substraction (scalar and matrix), let's see the example:

In [54]:
m_3 = np.array([np.arange(1,4), np.arange(4,7)])
m_4 = np.array([np.arange(7,10), np.arange(10,13)])
print("Matrix_3: ")
print(m_3)
print("Matrix_4: ")
print(m_4)


# Scalar substraction of 3 to each element in m_3
print("Scalar substraction: ")
print(m_3 - 3)


# Matrix addition of m_3 and m_4
print("substraction of two matrices of equal order: ")
print(m_3 - m_4)

Matrix_3: 
[[1 2 3]
 [4 5 6]]
Matrix_4: 
[[ 7  8  9]
 [10 11 12]]
Scalar substraction: 
[[-2 -1  0]
 [ 1  2  3]]
substraction of two matrices of equal order: 
[[-6 -6 -6]
 [-6 -6 -6]]


### Multiplication

Here we can have a little bit more complicated multiplication depending on shapes, but first we can start showing an example of element-wise multiplication:

In [66]:
matrix_e_w_m = np.array([np.arange(1,4), np.arange(4,7)])
print("Matrix: ")
print(matrix_e_w_m)

# division by scalar
print("Scalar Multiplication: ")
print(matrix_e_w_m * 5)

Matrix: 
[[1 2 3]
 [4 5 6]]
Scalar Multiplication: 
[[ 5 10 15]
 [20 25 30]]


Aditional to element-wise multiplication, we have an special kind called the matrix product, which is something like this:

$$
\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6 \\7 & 8 & 9 \end{bmatrix} · \begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6 \\7 & 8 & 9 \end{bmatrix} = \begin{bmatrix}30 & 36 & 42 \\66 & 81 & 96 \\102 & 126 & 150 \end{bmatrix}
$$

Okay, let's clearify this, What is happening? 
For that, we will explain using a vector dot product: 

$$
\begin{bmatrix}0 & 2 & 4 & 6\end{bmatrix} · \begin{bmatrix}1 & 7 & 13 &19\end{bmatrix}
$$
To find that dot product, first we multiply the corresponding elements of each vector:

(0 x 1) (2 x 7) (4 x 13) (6 x 19)

Then we add up all those results to get a single number:

(0 x 1) + (2 x 7) + (4 x 13) + (6 x 19) = 0 + 14 + 52 + 114 = 180

This operation let's us take two vectors of any length, as long as they are equal, and convert those vectors into a single number, so how does that help us multiply two matrices?

It turns out, to find the product of two matrices we take a series of products between every row in the left matrix and every column in the matrix. **Very important to remember**.

Whenever you multiply two matrices, you are actually dealing with the rows of the first matrix and the columns of the second matrix, so for our matrix we can start operating by this way:

(1 x 1) (2 x 4) (3 x 7) = 1 + 8 + 21 = 30

So `30` will be on our position (row_1,column_1), yes, now make sense. Lets continue with row_1 and column_2:

(1 x 2) (2 x 5) (3 x 8) = 2 + 10 + 24 = 36

Again, `36` matches with our position (row_1, column_2), and we can go so on. Try it by yourself!

You can find more information about [dot products](https://en.wikipedia.org/wiki/Dot_product)

### Division

Element-wise scalar division can be performed with the division operator `/`:

In [56]:
m_5 = np.array([np.arange(1,4), np.arange(4,7)])
print("Matrix_5: ")
print(m_5)

# division by scalar
print("Scalar Division: ")
print(m_5 / 2)

Matrix_5: 
[[1 2 3]
 [4 5 6]]
Scalar Division: 
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


### Exponents

Element-by-element exponent determination can be performed with the operator `**`:

In [58]:
m_6 = np.array([np.arange(1,4), np.arange(4,7)])
print("Matrix: ")
print(m_6)


# Raising each element in matrix to power 3
print("Matrix raised to power of 3: ")
print(m_6 ** 3)

Matrix: 
[[1 2 3]
 [4 5 6]]
Matrix raised to power of 3: 
[[  1   8  27]
 [ 64 125 216]]


### Matrix slicing

A matrix slice is the finding of a sub-matrix. Slicing utilizes the mentioned syntax:
- Matrix `[row index range, column index range, steps number]`
- Row and column index ranges follow the typical starting index Python syntax: end index.
- The selected range is all from the beginning index to (end index-1) while the code is running.

#### Slicing to choose a row:

In [60]:
m_7 = np.array([np.arange(1,5), np.arange(4,8)])
print("Matrix: ")
print(m_7)


# Slice to have 2nd row in matrix
print("result: ")
print(m_7[1:, :])

Matrix: 
[[1 2 3 4]
 [4 5 6 7]]
result: 
[[4 5 6 7]]


#### Slicing to choose a column:

In [61]:
m_8 = np.array([np.arange(1,5), np.arange(4,8)])
print("Matrix: ")
print(m_8)


# Slice to have 2nd row in matrix
print("result: ")
print(m_8[:, 2:])

Matrix: 
[[1 2 3 4]
 [4 5 6 7]]
result: 
[[3 4]
 [6 7]]


#### Slicing to choose a sub-matrix:

In [62]:
m_9 = np.array([np.arange(1,5), np.arange(5,9), np.arange(9,13), np.arange(13,17)])
print("Matrix: ")
print(m_9)
# Slice to get (2, 2) submatrix in the centre of mat_2d
print("sliced matrix:  ")
print(m_9[1:3, 1:3])

Matrix: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sliced matrix:  
[[ 6  7]
 [10 11]]
