<a href="https://colab.research.google.com/github/samuelkb/gColab/blob/main/notebooks/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducing NumPy

Python by itself is a good language but sometimes can be slow, specially when you work with ML / AI / DL. But fortunatelly, it does allow you to access to libraries that execute faster code written in languges like C.
NumPy is one such library, it provides fast alternatives to math operations in Python and is designed to work efficiently with groups of numbers - like matrices.

NumPy is a large library. In this notebook I will be updating some common uses, before to that, it could be interesting if you go and spend some time exploring its [documentation](https://docs.scipy.org/doc/numpy/reference/).

### Importing NumPy

The most used conventions you'll see is to name it "np" like so:

In [2]:
import numpy as np

Now you can use the library by prefixing the names of functions and types with np.

### Data types and shapes

The most common way to work with numbers in NumPy is through ndarray objects. They are similar to Python lists, but can have any number of dimensions. Also, ndarray supports fast math operations, which is just what we want.

Since it can store any number of dimensions, you can use ndarrays to represent any of the data types we covered before: scalars, vectors, matrices, or tensors.

### Scalars

[Scalars in NumPy](https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html) are a bit more involved than in Python. Instead of Python’s basic types like int, float, etc., NumPy lets you specify signed and unsigned types, as well as different sizes. So instead of Python’s int, you have access to types like uint8, int8, uint16, int16, and so on.

These types are important because every object you make (vectors, matrices, tensors) eventually stores scalars. And when you create a NumPy array, you can specify the type - **but every item in the array must have the same type.** In this regard, NumPy arrays are more like C arrays than Python lists.

If you want to create a NumPy array that holds a scalar, you do so by passing the value to NumPy's array function, like so:

In [2]:
s = np.array(5)

You can see the shape of your arrays by checking their `shape` attribute executing this code:

In [3]:
s.shape

()

For now, it is indicating us that it has zero dimensions.

Even though scalars are inside arrays, you still use them like a normal scalar. So we could type:

In [4]:
x = s + 3

And `X` would now equal to 8, and we can check the type of `X`, finding it is `numpy.int64`

In [21]:
print(x)

print(type(x))

8
<class 'numpy.int64'>


By the way, even scalar types support most of the array functions, so you can call ```x.shape```, and again it returns `()` because it has zero dimensions, even though it is not an array.

In [10]:
x.shape

()

If we try that with a normal Python scalar, we will get an error:

In [23]:
a = 10

print (a)

print(type(a))

a.shape

10
<class 'int'>


AttributeError: 'int' object has no attribute 'shape'

### Vectors

To create a vector, you'd pass a Python list to the `array` function, like this:

In [24]:
v = np.array([1,2,3])

Let's check its shape, we expect a single number representating the vector's one-dimensional length.

In [25]:
v.shape

(3,)

We can see that the shape is a tuple with the sizes of each of the `ndarray`'s dimensions. For scalars it was just an empty tuple, but vectors have one dimension, so the tuple includes a number and a comma.

You can access an element within the vector using indices, like this:

In [27]:
y = v[1]
print(y)

2


NumPy also supports advanced indexing techniques. For example, to access the items from the second element onward, you would say:

In [28]:
v[1:]

array([2, 3])

You can do a lot with NumPy indexing, I recommend you to read up on it [in the docs](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

According to docs, the basic slice syntax is ``i:j:k`` where ``i`` is the starting index, ``j`` is the stopping index, and ``k`` is the step (k $\neq$ 0). So we have the following:

In [3]:
x = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
print(x[1:7:2])

[10 30 50]


In [5]:
x = np.array([0, 11, 22, 33, 44, 55, 66, 77, 88, 99, 10, 20, 30, 40, 50])
x[1:10:4]

array([11, 55, 99])

### Matrices

To create matrices using NumPy you should use ```array``` function, as you did with vectors. However, instead of just passing in a list, you need to supply a list of lists, where each list represents a row.

To create a 3x3 matrix containing the numbers one through nine, you could do this:

In [7]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


If we check its ```shape``` attribute, we will recieve:

In [9]:
m.shape

(3, 3)

To access elements of matrices you will use indexes ```Row x Column```, for example, to access to number 6 of the above matrix, you can use:

In [10]:
print(m[1][2])

6


Here a little matrix shows how it indexes works in matrices:

In [13]:
matrix_order = np.array([['R0/C0','Col1','Col2','Col3'],['Row1',1,2,3],['Row2',4,5,6],['Row3',7,8,9]])
print(matrix_order)

[['R0/C0' 'Col1' 'Col2' 'Col3']
 ['Row1' '1' '2' '3']
 ['Row2' '4' '5' '6']
 ['Row3' '7' '8' '9']]


### Tensors

Tensors are just like vectors and matrices, but they can have more dimensions. To understand it, here an example of vector:

In [15]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

If you check its shape, you will find the following, also notice how it looks when we print the tensor:

In [18]:
t.shape

(3, 3, 2, 1)

In [19]:
print(t)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]


### Changing Shapes

Well, now you are familiar with how NumPy works with escalar, vectors, matrices and tensors. But you will discover that sometimes you would need to chang the shape of your data without actually changing its contents.
Let's say that we have a vector, witch is one-dimensional, but we need a matrix, wich is two-dimensional. To achieve that operation, we use ```reshape```function.
An example for better understanding:

In [20]:
v_to_reshape = np.array([10,20,30,40])
v_to_reshape.shape

(4,)

If we want a matrix 4x1, we can do this:

In [24]:
v_reshaped = v_to_reshape.reshape(4, 1)
v_reshaped.shape

(4, 1)

In [25]:
print(v_to_reshape)
print(v_reshaped)

[10 20 30 40]
[[10]
 [20]
 [30]
 [40]]
